-- Q1: Total revenue generated by the store
SELECT ROUND(SUM(unit_price * quantity), 2) AS total_revenue
FROM invoice_line;
-- Insight: Store ki total revenue 4709.43 hai. Yeh baaki sab analysis
-- (country, customer, artist, trend) ka baseline hai.

-- Q2: Revenue by country (highest first)
SELECT c.country,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM customer c
JOIN invoice i       ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id  = il.invoice_id
GROUP BY c.country
ORDER BY revenue DESC;

-- Q3: Top 10 customers by total spending
SELECT c.customer_id,
       c.first_name || ' ' || c.last_name AS customer_name,
       c.country,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS total_spent
FROM customer c
JOIN invoice i       ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id  = il.invoice_id
GROUP BY c.customer_id, customer_name, c.country
ORDER BY total_spent DESC
LIMIT 10;

-- Q4: Top 10 artists by revenue
SELECT ar.name AS artist,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM artist ar
JOIN album al        ON ar.artist_id = al.artist_id
JOIN track t         ON al.album_id  = t.album_id
JOIN invoice_line il ON t.track_id   = il.track_id
GROUP BY ar.artist_id, ar.name
ORDER BY revenue DESC
LIMIT 10;

-- Q5: Most popular genres (by units sold)
SELECT g.name AS genre,
       SUM(il.quantity) AS units_sold,
       RANK() OVER (ORDER BY SUM(il.quantity) DESC) AS popularity_rank
FROM genre g
JOIN track t         ON g.genre_id = t.genre_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY g.genre_id, g.name
ORDER BY units_sold DESC;

-- Q6: Top 10 albums by sales revenue
SELECT al.title AS album,
       ar.name AS artist,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM album al
JOIN artist ar       ON al.artist_id = ar.artist_id
JOIN track t         ON al.album_id  = t.album_id
JOIN invoice_line il ON t.track_id   = il.track_id
GROUP BY al.album_id, al.title, ar.name
ORDER BY revenue DESC
LIMIT 10;

-- Q7: Top 10 most frequently purchased tracks
SELECT t.name AS track,
       SUM(il.quantity) AS times_purchased
FROM track t
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY t.track_id, t.name
ORDER BY times_purchased DESC
LIMIT 10;

-- Q8: Average customer spending (CTE)
WITH customer_spend AS (
    SELECT c.customer_id,
           SUM(il.unit_price * il.quantity) AS total_spent
    FROM customer c
    JOIN invoice i       ON c.customer_id = i.customer_id
    JOIN invoice_line il ON i.invoice_id  = il.invoice_id
    GROUP BY c.customer_id
)
SELECT ROUND(AVG(total_spent), 2) AS avg_customer_spending
FROM customer_spend;

-- Q9: Customers who have never made a purchase (LEFT JOIN)
SELECT c.customer_id,
       c.first_name || ' ' || c.last_name AS customer_name,
       c.country
FROM customer c
LEFT JOIN invoice i ON c.customer_id = i.customer_id
WHERE i.invoice_id IS NULL;
-- Insight: Query se koi row nahi aayi, yani sabhi customers ne kam se kam
-- ek purchase kiya hai. Koi inactive/never-purchased customer segment nahi hai.

SELECT m.name AS tbl, p.name AS col
FROM sqlite_master m
JOIN pragma_table_info(m.name) p
WHERE m.type = 'table'
  AND m.name IN ('customer', 'invoice', 'employee')
ORDER BY m.name, p.cid;

-- Q10: Employees supporting the highest-value customers
SELECT e.employee_id,
       e.first_name || ' ' || e.last_name AS employee,
       COUNT(DISTINCT c.customer_id) AS customers_supported,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue,
       ROUND(SUM(il.unit_price * il.quantity) / COUNT(DISTINCT c.customer_id), 2) AS revenue_per_customer
FROM employee e
JOIN customer c      ON e.employee_id = c.support_rep_id
JOIN invoice i       ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id  = il.invoice_id
GROUP BY e.employee_id, employee
ORDER BY revenue DESC;

-- Q11: Percentage of revenue from each country (window function)
SELECT c.country,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue,
       ROUND(100.0 * SUM(il.unit_price * il.quantity)
             / SUM(SUM(il.unit_price * il.quantity)) OVER (), 2) AS pct_of_total
FROM customer c
JOIN invoice i       ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id  = il.invoice_id
GROUP BY c.country
ORDER BY revenue DESC;

-- Q12: Genres by revenue (top one is the highest)
SELECT g.name AS genre,
       ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM genre g
JOIN track t         ON g.genre_id = t.genre_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY g.genre_id, g.name
ORDER BY revenue DESC
LIMIT 5;

-- Q13: Monthly revenue trend with month-over-month growth (CTE + LAG)
WITH monthly AS (
    SELECT strftime('%Y-%m', i.invoice_date) AS month,
           SUM(il.unit_price * il.quantity) AS revenue
    FROM invoice i
    JOIN invoice_line il ON i.invoice_id = il.invoice_id
    GROUP BY month
)
SELECT month,
       ROUND(revenue, 2) AS revenue,
       ROUND(LAG(revenue) OVER (ORDER BY month), 2) AS prev_month,
       ROUND(100.0 * (revenue - LAG(revenue) OVER (ORDER BY month))
             / LAG(revenue) OVER (ORDER BY month), 2) AS growth_pct
FROM monthly
ORDER BY month;

-- Q14: Artists with the largest number of tracks
SELECT ar.name AS artist,
       COUNT(t.track_id) AS track_count
FROM artist ar
JOIN album al ON ar.artist_id = al.artist_id
JOIN track t  ON al.album_id  = t.album_id
GROUP BY ar.artist_id, ar.name
ORDER BY track_count DESC
LIMIT 10;

-- Q15: Customers with above-average spending (CTE + subquery + CASE)
WITH customer_spend AS (
    SELECT c.customer_id,
           c.first_name || ' ' || c.last_name AS customer_name,
           c.country,
           SUM(il.unit_price * il.quantity) AS total_spent
    FROM customer c
    JOIN invoice i       ON c.customer_id = i.customer_id
    JOIN invoice_line il ON i.invoice_id  = il.invoice_id
    GROUP BY c.customer_id, customer_name, c.country
)
SELECT customer_id,
       customer_name,
       country,
       ROUND(total_spent, 2) AS total_spent,
       CASE WHEN total_spent >= 1.2 * (SELECT AVG(total_spent) FROM customer_spend)
            THEN 'High Value' ELSE 'Above Average' END AS segment
FROM customer_spend
WHERE total_spent > (SELECT AVG(total_spent) FROM customer_spend)
ORDER BY total_spent DESC;


